package dk.n4;

public class Opgave3_4 { //Klasse ved navn Opgave3_4

    public static void main(String[] args) { //Programeksekvering

        int month = (int)(Math.random() * 13); //Deklarerer variablen "month" og genererer et tilfældigt tal mellem 0 og 12
        String monthString; //Deklarerer variablen "monthString", vi senere bruger til at udskrive hvilken måned, der blev genereret
        //System.out.println(month); //Udskriver hvilken måned, der blev genereret (lavet til debugging)

        System.out.print("Autogenerated Month is  //Udskriver til konsollen

        switch ( month ) { //Starter et switch-statement baseret på variablen "month"
            case 1: //Vi tester for værdien 1
                monthString = "January"; //Hvis "monthString" er 1 udskrives teksten "January"
                break;
            case 2: //Vi tester for værdien 2
                monthString = "February"; //Hvis "monthString" er 2 udskrives teksten "February" osv. dernedad
                break;
            case 3:
                monthString = "March";
                break;
            case 4:
                monthString = "April";
                break;
            case 5:
                monthString = "May";
                break;
            case 6:
                monthString = "June";
                break;
            case 7:
                monthString = "July";
                break;
            case 8:
                monthString = "August";
                break;
            case 9:
                monthString = "September";
                break;
            case 10:
                monthString = "October";
                break;
            case 11:
                monthString = "November";
                break;
            case 12:
                monthString = "December";
                break;
            default:
                monthString = "Invalid month"; //Hvis "monthString" ikke er et tal mellem 1 og 12 udskrives "Invalid month"
                break;
        }

        System.out.println(monthString); //Udskriver hvilken case det auto-genererede tal blev

    }

}
